export { moveDown } from './moveDown'
export { moveUp } from './moveUp'
export { moveRight } from './moveRight'
export { moveLeft } from './moveLeft'
export { addNewCell } from './addNewCell'
export { selectMoveFunc } from './selectMoveFunc'
export { checkGameOver } from './checkGameOver'
