export { default as Board } from './Board'
export { default as BackgroundBoard } from './BackgroundBoard'
export { default as Header } from './Header'
export { default as StartBox } from './StartBox'
export { default as Gameover } from './Gameover'
